# Generated by Django 5.1.3 on 2026-03-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumpbudget_app', '0004_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='additional_unpaid_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employer_full_pay_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employer_half_pay_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='taking_additional_unpaid',
            field=models.BooleanField(default=False),
        ),
    ]
