# Generated by Django 5.1.3 on 2026-03-20 19:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumpbudget_app', '0005_userprofile_additional_unpaid_weeks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.PositiveIntegerField()),
                ('week_end', models.PositiveIntegerField()),
                ('tip_label', models.CharField(blank=True, max_length=80)),
                ('tip_text', models.TextField()),
            ],
            options={
                'ordering': ['week_start'],
            },
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='expense',
            name='is_upcoming',
            field=models.BooleanField(default=False, help_text='Planned future expense — not yet spent'),
        ),
        migrations.AddField(
            model_name='expense',
            name='milestone',
            field=models.CharField(blank=True, choices=[('', 'None'), ('scan', 'Scan / appointment'), ('birth_prep', 'Birth preparation'), ('shower', 'Baby shower'), ('nursery', 'Nursery setup'), ('postbirth', 'Post-birth')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='budget_goal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly pregnancy/baby spending target', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('prenatal', 'Prenatal care'), ('nursery', 'Nursery'), ('clothing', 'Clothing & gear'), ('health', 'Health & vitamins'), ('childcare', 'Childcare'), ('food', 'Food'), ('transport', 'Transport'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General'), ('costs', 'Costs & budgeting'), ('week', 'Week by week'), ('maternity', 'Maternity leave'), ('nursery', 'Nursery & gear'), ('wellbeing', 'Wellbeing')], default='general', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False, help_text='Hide your name on this post')),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False, help_text='Hidden by staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='bumpbudget_app.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('saved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('color', models.CharField(choices=[('purple', 'Purple'), ('teal', 'Teal'), ('coral', 'Coral'), ('blue', 'Blue'), ('green', 'Green'), ('amber', 'Amber')], default='purple', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('prenatal', 'Prenatal care'), ('nursery', 'Nursery'), ('clothing', 'Clothing & gear'), ('health', 'Health & vitamins'), ('childcare', 'Childcare'), ('food', 'Food'), ('transport', 'Transport'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=50)),
                ('budget_limit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='bumpbudget_app.post')),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
    ]
