# Generated by Django 5.1.3 on 2026-04-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumpbudget_app', '0007_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='child_age_months',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='life_stage',
            field=models.CharField(choices=[('EXPECTING', 'Expecting (pregnant)')], default='EXPECTING', max_length=20),
        ),
    ]
