# Generated by Django 5.1.3 on 2026-04-23 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bumpbudget_app', '0008_remove_userprofile_child_age_months_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='savings_deadline',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='savings_goal_total',
        ),
    ]
