# Generated by Django 5.1.3 on 2026-04-23 23:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumpbudget_app', '0009_remove_userprofile_savings_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='savings_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='savings_goal_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
